### ISSUE TITLE
BotOnAndroid

### ISSUE THREAD

**Issue by Nucito** [guilhermej/dino_chrome_bot#1]
Olá Amigo Desculpe Se Não e Para Postar Isso Aqui Mais Seria Possível usar a Library "pillow" no Android? 
Achei bastante interessante

_Sent from my Motorola XT1069 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by guilhermej** [comment]
Provavelmente não.
https://github.com/kivy/python-for-android/issues/853
https://github.com/python-pillow/Pillow/issues/1957
https://stackoverflow.com/questions/38557731/how-to-import-python-pil-on-android-and-kivy
